### PR TITLE
Add typescript typings.

### PR DESCRIPTION
**Pull request by NaridaL**
Great lib, did exactly what I wanted with minimal hassle! 🥳 

I didn't see typescript typings here or on definitelytyped, so I thought I'd create some.

Should work out of the box for TypeScript users of the package.

### CODE REVIEW

**Review by binaryhq — APPROVED** [review]
Thanks!

**Comment by joewestcott** [comment]
Thanks for this @NaridaL! Although I did notice a copy/paste issue on line 24 :)

**Comment by NaridaL** [comment]
I fixed line 24.

**Comment by PascalPixel** [comment]
```log
  node_modules/svg-to-pdfkit/index.d.ts:14:5
    14     x: number,
           ~~~~~~~~~
    An argument for 'x' was not provided.
```

**Comment by NaridaL** [comment]
@PascalPixel the README doesn't say those parameters are optional, so I added them as required.

**Comment by cacalo** [comment]
@alafr is it possible for you to merge this PR? Thank you!

**Pull request merged**
